apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: charlierlee-com-route53-dns
  namespace: istio-system
spec:
  secretName: charlierlee-com-route53-dns-tls
  issuerRef:
    name: letsencrypt-staging-dns
    kind: Issuer
  dnsNames:
    - "charlierlee.com"
    - "*.charlierlee.com"