apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: leenet-lol-route53-dns
  namespace: istio-system
spec:
  secretName: leenet-lol-route53-dns-tls
  issuerRef:
    name: letsencrypt-staging-dns
    kind: Issuer
  dnsNames:
    - "leenet.lol"
    - "*.leenet.lol"