apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zambonigirl-com-route53-dns
  namespace: istio-system
spec:
  secretName: zambonigirl-com-route53-dns-tls
  issuerRef:
    name: letsencrypt-staging-dns
    kind: Issuer
  dnsNames:
    - "zambonigirl.com"
    - "*.zambonigirl.com"