apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: leenet-route53-dns
  namespace: default
spec:
  secretName: leenet-route53-dns-tls
  issuerRef:
    name: letsencrypt-staging-dns
    kind: Issuer
  dnsNames:
    - "leenet.link"
    - "*.leenet.link"