apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress-deploy-k8s-route53-dns
  namespace: default
  annotations:
    kubernetes.io/ingress.class: public # kubernetes.io/ingress.class: voyager does not work
    cert-manager.io/issuer: "letsencrypt-staging-dns"
    cert-manager.io/acme-challenge-type: dns01
spec:
  tls:
    - hosts:
        - "leenet.link"
        - "*.leenet.link"
      secretName: leenet-route53-dns-tls
  rules:
    - host: leenet.link
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: csharpauth
              port: 
                number: 80
    - host: www.leenet.link
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: csharpauth
              port: 
                number: 80
    - host: generate.leenet.link
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: generate
              port: 
                number: 8502
    - host: summary.leenet.link
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: summary
              port: 
                number: 8501
    